endpoint: https://jira.d2iq.com
user: maxjonaswerner
password-source: keyring
project: D2IQ
custom-commands:
  - name: flakes
    script: |-
      {{jira}} list --template table --query "labels = mergebot-override AND status != Resolved"
  - name: sprint
    help: display issues for active sprint
    options:
      - name: resolved
        short: r
        type: bool
      - name: all
        short: a
        type: bool
    script: |-
      SPRINT=2386
      EPIC=D2IQ-75137
      {{jira}} list --template table --query "sprint = $SPRINT and type != epic {{if not options.all}}and assignee = currentUser(){{end}} {{if not options.resolved}}and resolution = unresolved{{end}} and project=$JIRA_PROJECT and (key = $EPIC OR \"Epic Link\" = $EPIC OR issueFunction in subtasksOf(\"'Epic Link'=$EPIC\")) ORDER BY rank asc, created"
